base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

news_article/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'article_page/', index, name = 'article'),
    url(r'^hub/article/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', generate_article_page, name='generate_article_page'),
]

urlpatterns += staticfiles_urlpatterns()

newsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index
from project_hub.views import get_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', index, name = 'index'),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('about.urls','about'),namespace='about')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('donate.urls','donate'),namespace='donate')),
    path('', include(('project_hub.urls','project_hub'),namespace='project_hub')),
    path('', include(('project_item.urls','project_item'),namespace='project_item')),
    path('', include(('news_article.urls','news_article'),namespace='news_article')),
    path('',include(('user_profile.urls','user_profile'),namespace='user_profile')),
    url(r'^hub/', include(('project_hub.urls', 'project_hub'), namespace='project_hub')),
    url(r'projects/$', get_projects, name='get_projects'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'hub/', index, name = 'hub'),
    url(r'projects/$', get_projects, name='get_projects'),
]

urlpatterns += staticfiles_urlpatterns()

project_hub/models.py
from django.db import models

# Create your models here.

project_hub/views.py
from django.shortcuts import render
from news_article.models import Article
from project_item.models import Project
from django.http import JsonResponse

# Create your views here.
def index(request):
    
    all_article = Article.objects.order_by('id').all()
    
    top_article_first = all_article.first()
    all_article = all_article[1:]
    
    return render(request, 'hub.html', {'first_article':top_article_first,
                                        'all_article':all_article,
                                        'range':range(1,all_article.count()+1),
                                        'nbar': 'hub'})

def get_projects(request):
    category = request.GET.get('category', None)
    response = []
    
    if(category == "All"):
        projects = Project.objects.all()
    else:
        projects = Project.objects.filter(category=category)
        
    projects = projects.order_by('title')
        
    for project in projects:
        response.append({
            'title' : project.title,
            'slug' : project.slug_title(),
            'summary' : project.summary,
            'id' : project.id,
            'progress' : project.get_progress()
        })
    
    return JsonResponse(response, safe=False)

project_hub/templates/hub.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<style>
    .carousel-inner img{
        max-height: 602px;
        min-height: 602px;
    }
    
    @media screen and (max-width: 750px) {
        .d-manual{
            display: none;
        }
        
        .carousel-inner img{
            max-height: 370px;
            min-height: 370px;
        }
    }
    
    @media screen and (max-width: 550px) {
        .carousel-inner img{
            max-height: 250px;
            min-height: 250px;
        }
    }
</style>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        {% for idx in range %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{ idx }}"></li>
        {% endfor %}
    </ol>
    
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 img-fluid" src="{{ first_article.get_image }}">

            <div class="carousel-caption d-md-block">
                <a class="link-undecor text-light" href="{% url 'news_article:generate_article_page' first_article.id first_article.slug_title %}">
                    <h5>{{ first_article.title }}</h5>
                </a>
                <span class="d-manual">
                    {{ first_article.content|safe|truncatewords:60 }}
                </span>
            </div>
        </div>
        
        {% for article in all_article %}
        <div class="carousel-item">
            <img class="d-block w-100" src="{{ article.get_image }}" alt="Second slide">
            
            <div class="carousel-caption d-md-block">
                <a class="link-undecor text-light" href="{% url 'news_article:generate_article_page' article.id article.slug_title %}">
                    <h5>{{ article.title }}</h5>
                </a>
                <span class="d-manual">
                    {{ article.content|safe|truncatewords:60 }}
                </span>
            </div>
        </div>
        {% endfor %}
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container my-5">    
    <select title="Select A Category" class="custom-select mb-4" id="select-category">
        <option>All</option>
        <option><i class='glyphicon glyphicon-cutlery'>Earthquake</i></option>
        <option>Hurricane</option>
        <option>Tsunami</option>
    </select>
    <div id="projects-container"></div>
</div>

<script>    
    $(document).ready(function() {
        getProjectsData($('#select-category').val());
        
        $("#select-category").change(function(){
            var selected = $('#select-category').val();
            getProjectsData(selected);
        });
        
        function getProjectsData(category){
            console.log(category);
            $.ajax({
                url: "/get_projects/",
                type: "GET",
                data: {category: category},
                success: function(data){
                    var project_cards = '<div class="maProjects row">';
                    $.each(data, function(key, value){
                        project_cards += '<div class="col-sm-4 mb-4">';
                        project_cards += '<div class="card">';
                        project_cards += '<div class="card-body">';
                        project_cards += '<h5 class="card-title">'+ value.title +'</h5>';
                        project_cards += '<h6 class="card-subtitle mb-2 text-muted">'+ value.summary +'</h6>';
                        project_cards += '<div class="progress">';
                        project_cards += '<div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" '
                        project_cards += 'aria-valuenow="'+ value.progress +'" aria-valuemin="0" aria-valuemax="100" style="width: '+ value.progress +'%">';
                        project_cards += '</div></div>';
                        project_cards += '<a href="/hub/project/'+ value.id +'/'+ convertToSlug(value.title) +'/" class="card-link">';
                        project_cards += '<button class="btn btn-warning mt-3 text-white">donate</button></a>';
                        project_cards += '</div></div></div>';
                    });

                    $(".maProjects").remove();
                    $('#projects-container').append(project_cards+="</div>");  
                }
            });
        }
    });
</script>

{% endblock %}