base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

news_article/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'article_page/', index, name = 'article'),
    url(r'^hub/article/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', generate_article_page, name='generate_article_page'),
]

urlpatterns += staticfiles_urlpatterns()

newsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index
from project_hub.views import get_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', index, name = 'index'),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('about.urls','about'),namespace='about')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('donate.urls','donate'),namespace='donate')),
    path('', include(('project_hub.urls','project_hub'),namespace='project_hub')),
    path('', include(('project_item.urls','project_item'),namespace='project_item')),
    path('', include(('news_article.urls','news_article'),namespace='news_article')),
    path('',include(('user_profile.urls','user_profile'),namespace='user_profile')),
    url(r'^hub/', include(('project_hub.urls', 'project_hub'), namespace='project_hub')),
    url(r'projects/$', get_projects, name='get_projects'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_item/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'projecthub/', index, name = 'project'),
    url(r'^hub/project/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', generate_project_page, name='generate_project_page'),
]

urlpatterns += staticfiles_urlpatterns()

news_article/models.py
from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static
from project_item.models import Project
import os, uuid

# Create your models here.
def get_image_path(instance, filename):
    return os.path.join('article', filename)

class Article(models.Model):
    title = models.CharField(max_length = 250)
    category = models.CharField(max_length = 500)   
    article_image = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    content = models.TextField(default="<p></p>")
    modified_date = models.DateTimeField(auto_now=True)
    projects = models.ManyToManyField(Project, blank=True)
    
    def slug_title(self):
        return self.title.replace(" ","-")
    
    @property
    def get_image(self):
        if(not self.article_image):
            return static("img/No_Image_Available.jpg")
        return self.article_image.url
    
    def __str__(self):
        return self.title

news_article/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound
from news_article.models import Article

# Create your views here.
def index(request):
	return render(request, 'article.html')

def generate_article_page(request, pk, slug):
    title = slug.replace("-", " ")    
    try:
        article = Article.objects.get(pk=pk, title=title)
        
    except Article.DoesNotExist:
        return HttpResponseNotFound("page not found")
    
    return render(request, 'article.html', {'article':article})

news_article/templates/article.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<style>
    #category{
        padding: 8px;
        color: yellow;
        background-color: orange;
    }
    
    .card img{
        max-height: 500px;
    }
</style>

<div class="container">
    <div class="card mb-3">
        <img class="d-block w-100" src="{{ article.get_image }}" alt="Third slide">
        <div class="card-body p-5">
            <h7 id="category">{{ article.category }}</h7>
            <br><br>
            <h1 class="card-title">{{ article.title }}</h1>
            {{ article.content|safe }}
            <p class="card-text"><small class="text-muted">Last updated {{ article.modified_date }}</small></p>
        </div>
    </div>

    <div class="row">
        <div class="container my-2">
            <h4>Related Projects :</h4>
        </div>
        {% for project in article.projects.all %}
        <div class="col-sm-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ project.summary }}</h6>

                    <div class="progress">
                        <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{ project.get_progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ project.get_progress }}%"></div>
                    </div>
                    <a href="{% url 'project_item:generate_project_page' project.id project.slug_title %}" class="card-link">
                        <button class="btn btn-warning mt-3 text-white">donate</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}