base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'login/', index, name = 'login'),
    path(r'logout/', logout, name = 'logout'),
]

urlpatterns += staticfiles_urlpatterns()

newsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index
from project_hub.views import get_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', index, name = 'index'),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('about.urls','about'),namespace='about')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('donate.urls','donate'),namespace='donate')),
    path('', include(('project_hub.urls','project_hub'),namespace='project_hub')),
    path('', include(('project_item.urls','project_item'),namespace='project_item')),
    path('', include(('news_article.urls','news_article'),namespace='news_article')),
    path('',include(('user_profile.urls','user_profile'),namespace='user_profile')),
    url(r'^hub/', include(('project_hub.urls', 'project_hub'), namespace='project_hub')),
    url(r'projects/$', get_projects, name='get_projects'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'hub/', index, name = 'hub'),
    url(r'projects/$', get_projects, name='get_projects'),
]

urlpatterns += staticfiles_urlpatterns()

user_profile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path('profile/', index, name = 'profile'),
    url(r'^get_json/',get_json,name='get_json'),
]

urlpatterns += staticfiles_urlpatterns()

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'index.html', {'nbar': 'index'})

base/templates/partials/footer.html
<!-- Footer -->
<footer id="footer" class="py-5 bg-theme">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; -My Website- Project2 PPW2018</p>
    </div>
</footer>

base/templates/partials/header.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-theme fixed-top">
    <div class="container">
        <a id="header-title" class="navbar-brand" href="#">Project 2</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'index' %}active{% endif %}" href="{% url 'base:index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'hub' %}active{% endif %}" href="{% url 'project_hub:hub' %}">Hub</a>
                </li>

                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link {% if nbar == 'profile' %}active{% endif %}" href="{% url 'user_profile:profile' %}">Profile</a>
                    <a href="{% url 'login:logout' %}"><button class="btn btn-danger"> Logout </button></a>

                    {% else %}
                    <a href="{% url 'login:login' %}" ><button class="btn btn-success"> Login </button></a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>