base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

donate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'donate/', index, name = 'donate'),
    url(r'^hub/project/(?P<pk>\d+)/(?P<slug>[-\w]+)/donate/$', generate_donation_page, name='generate_donation_page'),
    url(r'^ajax/donate/$', validate_donate, name='validate_donate'),
]

urlpatterns += staticfiles_urlpatterns()

newsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index
from project_hub.views import get_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', index, name = 'index'),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('about.urls','about'),namespace='about')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('donate.urls','donate'),namespace='donate')),
    path('', include(('project_hub.urls','project_hub'),namespace='project_hub')),
    path('', include(('project_item.urls','project_item'),namespace='project_item')),
    path('', include(('news_article.urls','news_article'),namespace='news_article')),
    path('',include(('user_profile.urls','user_profile'),namespace='user_profile')),
    url(r'^hub/', include(('project_hub.urls', 'project_hub'), namespace='project_hub')),
    url(r'projects/$', get_projects, name='get_projects'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_item/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'projecthub/', index, name = 'project'),
    url(r'^hub/project/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', generate_project_page, name='generate_project_page'),
]

urlpatterns += staticfiles_urlpatterns()

project_item/models.py
from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils.text import slugify
import os

# Create your models here.
def get_image_path(instance, filename):
    return os.path.join('article', filename)

class Patreon(models.Model):
    name = models.CharField(max_length = 300)
    donation = models.IntegerField(default = 1)
    
    def __str__(self):
        return self.name+" :: "+str(self.donation)
    
class Project(models.Model):
    title = models.CharField(max_length = 250)
    category = models.CharField(max_length = 500)
    summary = models.CharField(max_length = 500)
    content = models.TextField(default="<p></p>")
    image = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    modified_date = models.DateTimeField(auto_now=True)
    
    anonymous_donation = models.IntegerField(default=0)
    max_donation = models.IntegerField(default=100)
    
    patreon = models.ManyToManyField(Patreon, blank=True)
    
    def slug_title(self):
        return self.title.replace(" ","-")
    
    def get_progress(self):
        return self.current_donation() / self.max_donation * 100
    
    @property
    def get_image(self):
        if(not self.image):
            return static("img/No_Image_Available.jpg")
        return self.image.url
    
    def current_donation(self):
        total = self.anonymous_donation
        for patreon in self.patreon.all():
            total += patreon.donation
            
        return total
    
    def __str__(self):
        return self.title+" <> "+self.category

project_item/views.py
from django.shortcuts import render
from news_article.models import Project
from django.http import HttpResponseNotFound

# Create your views here.
def index(request):
	return render(request, 'project.html')

def generate_project_page(request, pk, slug):
    title = slug.replace("-", " ")    
    try:
        project = Project.objects.get(pk=pk, title=title)
        
    except Project.DoesNotExist:
        return HttpResponseNotFound("page not found")
    
    return render(request, 'project.html', {'project':project})

project_item/templates/project.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<style>
    #category{
        padding: 8px;
        color: yellow;
        background-color: orange;
    }
    
    .card img{
        max-height: 500px;
        border-style: solid;
        border-color: orange;
    }
</style>

<div class="container pt-4">
    <div class="row">
        <div class="col-sm-7 mb-3">
            <div class="p-3 card">
                <img class="d-block w-100" src="{{ project.get_image }}" alt="Third slide">
                <div class="card-body p-4">
                    <h7 id="category">{{ project.category }}</h7>
                    <br><br>
                    <h1 class="card-title">{{ project.title }}</h1>
                    <p class="card-text">{{ project.content|safe }}</p>
                    <p class="card-text"><small class="text-muted">Last updated {{ project.modified_date }}</small></p>
                </div>
            </div>
        </div>

        <div class="col-sm-5 mb-4">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2">Progress :</h6>

                    <div class="progress">
                        <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{ project.get_progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ project.get_progress }}%"></div>
                    </div>
                    
                    <div class="clearfix">
                        <p class="text-muted float-left">current: <span id="current-progress">{{ project.current_donation }}</span></p>
                        <p class="text-muted float-right">goal: <span id="current-progress">{{ project.max_donation }}</span></p>
                    </div>
                    
                    <a href="{% url 'donate:generate_donation_page' project.id project.slug_title %}"><button type="button" class="text-white btn btn-warning">Donate</button></a>
                </div>
            </div>
            
            <div class="card mt-3">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2">Patreon :</h6>                    
                    <ul class="mb-0">
                        {% for patreon in project.patreon.all %}
                        <li><span class="float-left">{{ patreon.name }}</span><span class="float-right pr-4">{{ patreon.donation }}</span></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}